name: All

on: [push]

jobs:
  all:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Source code styling
        run: make style
      - name: Linting
        run: make lint