name: All

on: [push]

jobs:
  all:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Source code styling
        run: swiftformat Mobs --maxwidth 90 --lint
      - name: Linting
        run: swiftlint lint --strict