name: All

on:
  push:
  pull_request:

jobs:
  all:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Source code styling
        run: |
          make style
      - name: Linting
        run: |
          make lint
      - name: Build
        run: |
          xcodebuild -scheme Moblin -destination 'platform=iOS,name=Any iOS Device' build
